import { createSlice } from "@reduxjs/toolkit";

// Define a slice for handling liked cards
export const likeSlice = createSlice({
  // Name of the slice
  name: "like",
  // Initial state of the slice
  initialState: {
    likedCards: [],
  },
  // Reducers to handle state changes
  reducers: {
    // Toggle like action: add or remove a card from liked cards
    toggleLike: (state, action) => {
      const index = state.likedCards.indexOf(action.payload);
      if (index === -1) {
        state.likedCards.push(action.payload);
      } else {
        state.likedCards.splice(index, 1);
      }
    },
    // Clear favorites action: remove all cards from liked cards
    clearFavs: (state) => {
      state.likedCards = [];
    },
  },
});

// Exporting actions generated by the slice
export const { toggleLike, clearFavs } = likeSlice.actions;

// Exporting the reducer function generated by the slice
export default likeSlice.reducer;
